### ISSUE TITLE
Insufficient permissions to invoke keep-alive on redeployment

### ISSUE THREAD

**Issue by cjkent** [cjkent/osiris#219]
There still seems to be a cold-start delay

**Comment by cjkent** [comment]
The first problem was this https://github.com/cjkent/osiris-examples/issues/14

Then there's this
```
2019-06-04 22:58:23.416 529d2c3b-edec-4453-a8aa-4dc3c1592fa1 DEBUG ws.osiris.aws.KeepAliveLambda - Triggering keep-alive, count: 1, function: arn:aws:lambda:eu-west-1:882408287024:function:osiris-lumigo-example:13
User: arn:aws:sts::882408287024:assumed-role/osiris-lumigo-example-ApiSta-KeepAliveFunctionRole-1E58RFF6WUDZF/osiris-lumigo-example-ApiStack-1-KeepAliveFunction-V3CHXFFVEIJU is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-west-1:882408287024:function:osiris-lumigo-example:13 (Service: AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Request ID: ad0f7df2-7bb4-4be2-8d9d-ccb186552092): com.amazonaws.services.lambda.model.AWSLambdaException
com.amazonaws.services.lambda.model.AWSLambdaException: User: arn:aws:sts::882408287024:assumed-role/osiris-lumigo-example-ApiSta-KeepAliveFunctionRole-1E58RFF6WUDZF/osiris-lumigo-example-ApiStack-1-KeepAliveFunction-V3CHXFFVEIJU is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-west-1:882408287024:function:osiris-lumigo-example:13 (Service: AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Request ID: ad0f7df2-7bb4-4be2-8d9d-ccb186552092)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:3255)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3222)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3211)
	at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1842)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1813)
	at ws.osiris.aws.KeepAliveLambda.handle(KeepAlive.kt:33)```
